import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Transition from "./components/Transition";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/">Index</Link>
            </li>
          </ul>
        </nav>
        <main>
          <Transition>{children}</Transition>
        </main>
      </body>
    </html>
  );
}
